# -*- mode: restclient; url-max-redirections: 0 -*-

##############################
# Constants

:host = http://localhost:8080

#
:content = <<
Content-Type: application/json
#

# Adam!
:a = <<
:content
dn: Adam!
#

##############################
# User

# Create
POST :host/user
:content
{
"email": "a"
}

# Read
GET :host/user/a
:content

# Update
PUT :host/user/a
:content
{
"email": "b"
}

# Delete
DELETE :host/user/a
:content

##############################
# GHCredential

# Step 1. Get a link for authorizing at the service
# Test with- C-c C-u to get curl command
# copy the redirect address
GET :host/github/authorize
dn: mrlink@gmail.com

# Step 2. Accept a callback from the service
GET :host/github/authorized?code=hooray

# Step 3. The token should have been persisted, use it!


##############################
# 

#
GET :host/

# Login
POST :host/login
:content
{
"email": "a",
"password": "a"
}

# Signup
POST :host/signup
:content
{
"email": "a",
"password": "a"
}
#
decode "{\"email\": \"hi\", \"password\": \"a\"}" :: Maybe ClearCredentials